services:
  - type: web
    name: acai-prime
    runtime: node
    region: oregon
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    healthCheckPath: /api/products
    envVars:
      - key: NODE_ENV
        value: production
